language: node_js

node_js:
  - node

branches:
  only:
    - master

before_script:
  - node --version
  - npm --version
  - npm install -g @angular/cli
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run e2e
