language: node_js

node_js:
  - node

addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - node --version
  - npm --version
  - npm install -g @angular/cli
  - npm install -g firebase-tools
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run e2e
  - npm run build
  - firebase deploy --token "$FIREBASE_TOKEN"
